# Ruby CircleCI 2.0 configuration file

version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.1
          PGHOST: localhost
          PGUSER: fast_tracks
          RAILS_ENV: test
      - image: postgres:11.3
        environment:
          POSTGRES_USER: fast_tracks
          POSTGRES_DB: fast_tracks_test
          POSTGRES_PASSWORD: ''

    working_directory: ~/fast_tracks

    steps:
      - checkout

      # Restore Cached Dependencies
      # - type: cache-restore
      #   name: Restore bundle cache
      #   key: fast_tracks-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run:
          command: |
            gem update --system
            gem install bundler:2.0.1
            bundle install

      # Cache Dependencies
      # - type: cache-save
      #   name: Store bundle cache
      #   key: fast_tracks-{{ checksum "Gemfile.lock" }}
      #   paths:
      #     - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # # Setup the environment
      # - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake
